### ISSUE TITLE
Disable SVGO by Default?

### ISSUE THREAD

**Issue by BrianSipple** [Hiswe/gulp-svg-symbols#22]
Hello,

I already have a separate workflow in place for optimizing my SVGs, and using this tool with the default settings completely overrides that, as it appears to use SVGO by default. 

I've been trying to tinker with the "svgoConfig" property in order to disable SVGO entirely, but to no avail. I'm wondering if there is a way to do so -- and if, for that matter, SVGO should only be enabled when someone explicitly sets the "svgoConfig" property.

Regardless of my own workflow, it seems to go against the stated goal of being a "minimal plugin" by having the default behaviour directly tied to SVGO.

Overall, though, great job! I really want to be using this as part of my SVG workflow.

Cheers.

**Comment by Hiswe** [comment]
Hi @BrianSipple 

You're totally right: this plugin shouldn't use SVGO.

I had worked on a [branch to remove SVGO](https://github.com/Hiswe/gulp-svg-symbols/tree/svgo-removal). This will fixes many [issues](https://github.com/Hiswe/gulp-svg-symbols/issues/6).
So you could use this branch instead of the published one.

I'm glad that you have a SVG workflow.
If you use the other branch, it'll be great if I can give me any feedbacks to improve the API or the behaviour of this plugin.
Right now I'm still confuse of what it should or shouldn't do :)

**Comment by Hiswe** [comment]
@BrianSipple finally done in v1.0.0 :)

**Comment by BrianSipple** [comment]
I just got around to checking back in on this... awesome -- and thanks!

**Comment by Hiswe** [comment]
You're welcome :)
