### ISSUE TITLE
Allow arbitrary attributes on <svg> element

### ISSUE THREAD

**Issue by fvsch** [Hiswe/gulp-svg-symbols#37]
Currently gulp-svg-symbols can output two attributes on a sprite's root element:

- `xmlns="http://www.w3.org/2000/svg"` is hardcoded
- `class="<%= svgClassname %>"` if options.svgClassname is truthy

While keeping all this in place, it would be useful for users to pass other attributes, which can vary depending on specific needs:
- varying `xmlns` declarations,
- `aria-hidden="true"` and maybe `style="/* let's hide this */"` for embedded sprites,
- other use cases I’m not thinking of

I suggest adding an `svgAttributes` option that will be passed to templates, and rendered like this:

```
<svg<%= renderAttributes({className: svgClassname}, svgAttributes) %>>
```
The `renderAttributes` function could be defined in the template itself (see the [attrs function here](https://github.com/gradientz/assets-builder/blob/master/assets-builder/tasks/svgsymbols-sprite.svg?short_path=5622458) for an example, though it would need to be extended to accept and merge several objects). Or it could be defined once and provided to all templates. That would bring the list of data provided to templates to:

- icons (Array)
- defs (string)
- renderAttributes (Function)
- svgClassname (user defined)
- svgAttributes (user defined)

(If I’m not missing anything.)

**Comment by Hiswe** [comment]
Hi,

That seems a really good idea :)

I think the `renderAttributes` function should be handled by the plugin. For what I see the main purpose would be to merge default attributes with custom, and convert `className` to `class`

- `svgClassname` should be deprecated: All attributes should be handled in `renderAttributes` (In order to prevent too many options)
-  `renderAttributes` should be an object or a function that return an object

This change could be handled without a major version.

Like I said for your PR, I don't have time right now, but I will try to improve this on January.

Thanks for this suggestion!

**Comment by Hiswe** [comment]
@fvsch done in 3.0.
Many thanks

**Comment by fvsch** [comment]
Congrats on shipping 3.0! 🎉 
And thanks for the nice mention in the README :heart:

**Comment by Hiswe** [comment]
Thanks for contributing :)
